# Generated by Django 2.0 on 2020-01-20 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='media/')),
                ('bio', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('goal1', models.CharField(max_length=50)),
                ('goal2', models.CharField(max_length=50)),
                ('goal3', models.CharField(max_length=50)),
                ('goal4', models.CharField(max_length=50)),
                ('goal5', models.CharField(max_length=50)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
